CREATE TABLE room(
    room_number INT PRIMARY KEY,
    room_type VARCHAR(15),
    capacity INT,
    available BOOLEAN
)

CREATE TABLE CLIENT(
    id_client INT PRIMARY KEY,
    name_client VARCHAR(30),
    addrress_client VARCHAR(50),
    phone VARCHAR(15),
    email VARCHAR(25),
    nationality VARCHAR(20),
)

CREATE TABLE BOOKING(
    id_order INT PRIMARY KEY,
    room_num INT FOREIGN KEY REFERENCES  room(ROOM_NUM),
    ID_CLIENT INT FOREIGN KEY REFERENCES CLIENT(ID_CLIENT),
    TIME_ORDER TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHECK_IN TIMESTAMP,
    CHECK_OUT TIMESTAMP 
)

CREATE TABLE BILL(
    ID_BILL INT PRIMARY KEY,
    DATE_BILL TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TOTAL_PRICE INT,
)

CREATE TABLE SERVICES(
    ID_SERVICES INT,

)